name: Sync stylish-login-mam to MAMS

on:
  push:
    branches:
      - main  # Change if your main branch is different

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout stylish-login-mam
        uses: actions/checkout@v3

      - name: Push to MAMS
        run: |
          git remote add mams https://github.com/your-username/MAMS.git
          git push --force mams main
